global:
  scrape_interval: 5s  # Интервал сбора метрик - каждые 5 секунд

scrape_configs:
  - job_name: 'prometheus'  # Название работы (job)
    static_configs:
      - targets: ['localhost:9090']  # Цели сбора метрик - локальный хост на порту 9090

  - job_name: 'node'  # Название работы (job)
    static_configs:
      - targets: ['localhost:9100']  # Цели сбора метрик - локальный хост на порту 9100

  - job_name: 'my_nodes'  # Название работы (job)
    static_configs:
      - targets: ['localhost:8080']  # Цели сбора метрик - локальный хост на порту 8080